<?php


namespace App\Repository\Product;

use App\Entity\Product\ProductFavourite;
use App\Entity\Vendor\VendorFavourite;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ProductsFavouritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFavouriteRepository extends EntityRepository
{
    /**
	 * @param VendorFavourite $vendor
	 * @param integer           $productId
	 *
     * @return bool
     * @throws NonUniqueResultException
     */
    public function checkIsLiked($vendor, $productId): ?bool
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(f.id)')
			->from(ProductFavourite::class, 'f')
            ->innerJoin('f.vendor', 'v')
            ->innerJoin('f.product', 'p')
            ->where('v = :vendor')
            ->andWhere('p.id = :product_id')
            ->setParameters([
                'product_id' => $productId,
                'vendor' => $vendor
            ]);

        if ($qb->getQuery()->getSingleScalarResult()) {
            return true;
        }

        return false;
    }
}
