<?php

return [
    'APP_SECRET' => null,
    'AWS_KEY' => null,
    'AWS_SECRET' => null,
    'AWS_TARGET_REGION' => null,
    'DATABASE_URL' => null,
    'FACEBOOK_OAUTH_ID' => null,
    'FACEBOOK_OAUTH_SECRET' => null,
    'FIREBASE_KEY' => null,
    'GITHUB_KEY' => null,
    'GITHUB_SECRET' => null,
    'GOOGLE_AUTH_ID' => null,
    'GOOGLE_AUTH_SECRET' => null,
    'GOOGLE_RECAPTCHA_KEY' => null,
    'GOOGLE_RECAPTCHA_SECRET' => null,
    'MAILER_DSN' => null,
    'OBJECT_REVIEW_DATABASE' => null,
    'PLATFORM_DATA_DATABASE' => null,
    'SMS_GATEWAY_ID' => null,
    'SMS_GATEWAY_PASSWORD' => null,
    'SMS_GATEWAY_SECRET' => null,
    'SMS_STATUS_SECRET' => null,
    'TWILIO_SID' => null,
    'TWILIO_TOKEN' => null,
];
