# https://api-platform.com/docs/core/configuration/
api_platform:
    default:
        normalization_context: ~
            denormalization_context: ~
            filters: ~
            mercure: ~
            messenger: ~
            order: ~

                # To enable or disable pagination for all resource collections.
                pagination_enabled: true

                # To allow the client to enable or disable the pagination.
                pagination_client_enabled: false

                # To allow the client to set the number of items per page.
                pagination_client_items_per_page: false

                # To allow the client to enable or disable the partial pagination.
                pagination_client_partial: false

                # The default number of items per page.
                pagination_items_per_page: 30

                # The maximum number of items per page.
                pagination_maximum_items_per_page: ~

                # To allow partial pagination for all resource collections.
                # This improves performances by skipping the `COUNT` query.
                pagination_partial: false

                # To use cursor-based pagination.
                pagination_via_cursor: ~

                pagination_fetch_join_collection: ~

                route_prefix: ~
                validation_groups: ~
                sunset: ~
                input: ~
                output: ~
                stateless: ~

                # The URL generation strategy to use for IRIs
                url_generation_strategy: !php/const ApiPlatform\Api\UrlGeneratorInterface::ABS_PATH
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]

    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        yaml: [ 'application/x-yaml' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]
