parameters:
  app_cache: 0
  app_cache_time: 360
  app_caching: '1'
  app_cache_handler: 'file'
  app_cachetime: '15'
  app_cache_platformprefix: '1'
  app_redis_persist: '1'
  app_redis_server_host: 'localhost'
  app_redis_server_port: '6379'
  app_redis_server_auth: ''
  app_redis_server_db: '0'
  app_session_redis_persist: '1'
  app_session_redis_server_host: 'localhost'
  app_session_redis_server_port: '6379'
  app_session_redis_server_auth: ''
  app_session_redis_server_db: '0'
  app_memcache_persist: '1'
  app_memcache_compress: '0'
  app_memcache_server_host: 'localhost'
  app_memcache_server_port: '11211'
  app_session_memcache_server_host: 'localhost'
  app_session_memcache_server_port: '11211'
  app_memcached_persist: '1'
  app_memcached_compress: '0'
  app_memcached_server_host: 'localhost'
  app_memcached_server_port: '11211'
  app_session_memcached_server_host: 'localhost'
  app_session_memcached_server_port: '11211'
