doctrine:
    dbal:
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType

        default_connection: postgres
        connections:
            postgres:
                # configure these for your database server
                # these connectors for all project's information
                url: '%env(PLATFORM_DATA_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!messenger_messages)~'
            review:
                url: '%env(resolve:OBJECT_REVIEW_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
            sqlite:
                # configure these for your database server
                # this connector for all modules, menus, parameters of system
                url: '%env(resolve:PLATFORM_SYSTEM_DATABASE)%'
                driver: 'pdo_sqlite'
                server_version: '3.21'
                charset: utf8mb4
    orm:
        resolve_target_entities:
            App\Interface\Category\CategoryInterface: App\Entity\Category\Category
            App\Interface\Category\CategoryAttachmentInterface: App\Entity\Category\CategoryAttachment
            #
            App\Interface\Project\ProjectInterface: App\Entity\Project\Project
            #
            App\Interface\Project\ProjectTypeInterface: App\Entity\Project\ProjectType
            App\Interface\Product\ProductTypeInterface: App\Entity\Product\ProductType
            #
            App\Interface\Featured\FeaturedInterface: App\Entity\Featured\Featured
            #
            App\Interface\Product\ProductReviewInterface: App\Entity\Product\ProductReview
            App\Interface\Product\ProjectReviewInterface: App\Entity\Project\ProjectReview

        default_entity_manager: postgres
        entity_managers:
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    Vendor:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Vendor'
                        prefix: 'App\Entity\Vendor'
                        alias: Vendor
                    Project:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: Project
                    Product:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: Product
                    Order:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Order'
                        prefix: 'App\Entity\Order'
                        alias: Order
                    Folder:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Folder'
                        prefix: 'App\Entity\Folder'
                        alias: Folder
                    Commission:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Commission'
                        prefix: 'App\Entity\Commission'
                        alias: Commission
                    Payment:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Payment'
                        prefix: 'App\Entity\Payment'
                        alias: Payment
                    Shipment:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Shipment'
                        prefix: 'App\Entity\Shipment'
                        alias: Shipment
                    Storage:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Storage'
                        prefix: 'App\Entity\Storage'
                        alias: Storage
                    Event:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Event'
                        prefix: 'App\Entity\Event'
                        alias: Event
                    Featured:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Featured'
                        prefix: 'App\Entity\Featured'
                        alias: Featured
                    # May be Module not need in this connection
                    Module:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
            review:
                connection: review
                mappings:
                    ProductReview:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: ProductReview
                    ProjectReview:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: ProjectReview
            sqlite:
                connection: sqlite
                mappings:
                    Menu:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Menu'
                        prefix: 'App\Entity\Menu'
                        alias: Menu
                    Module:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
                    Category:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
                    ProjectType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: ProjectType
                    ProductType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: ProductType
                    Locale:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Locale'
                        prefix: 'App\Entity\Locale'
                        alias: Locale
                    Zone:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Zone'
                        prefix: 'App\Entity\Zone'
                        alias: Zone
                    Exchange:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Exchange'
                        prefix: 'App\Entity\Exchange'
                        alias: Exchange
                    Currency:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Currency'
                        prefix: 'App\Entity\Currency'
                        alias: Currency
                    Taxation:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Taxation'
                        prefix: 'App\Entity\Taxation'
                        alias: Taxation
                    Coupon:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Coupon'
                        prefix: 'App\Entity\Coupon'
                        alias: Coupon
                    Payment:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Payment'
                        prefix: 'App\Entity\Payment'
                        alias: Payment
                    Association:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Association'
                        prefix: 'App\Entity\Association'
                        alias: Association
        auto_generate_proxy_classes: true
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
