enqueue:
#    default:
#        transport: '%env(resolve:ENQUEUE_DSN)%'
#        client: null
    testsns:
        transport:
            dsn: 'sns:'
            connection_factory_class: 'Enqueue\Sns\SnsConnectionFactory'
            key: '%env(AWS_KEY)%'
            secret: '%env(AWS_SECRET)%'
            region: '%env(AWS_TARGET_REGION)%'
        client: ~

# https://medium.com/tuitech/symfony-messenger-and-aws-sns-sqs-d010bfa06974
# https://github.com/php-enqueue/enqueue-dev
# https://julianli-co.translate.goog/articles/using-symfony-messenger-with-aws-sqs?_x_tr_sl=en&_x_tr_tl=ru&_x_tr_hl=ru&_x_tr_pto=op,sc
