framework:
    # see https://symfony.com/doc/current/reference/configuration/framework.html
    ide: 'phpstorm://open?file=file://%%f&line=%%l'
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    default_locale: '%app_locale%'
    translator:
        enabled_locales: [ 'en', 'ru' ]
        fallbacks: ['en']
        cache_dir: null

    #    hinclude_default_template: # См. Как встраивать асинхронный контент с помощью hinclude.js для получения дополнительной информации о hinclude.
    secrets:
        vault_directory: '%kernel.project_dir%/config/secrets/%kernel.environment%'
        local_dotenv_file: '%kernel.project_dir%/.env.%kernel.environment%.local'
        decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'

    validation:
#        mapping:
#            paths:
#                - "%kernel.project_dir%/config/validation/"
        not_compromised_password: false # in prod must by of true
#         validator.mapping.cache.doctrine.apc  # Симфони кеш
    error_controller: App\Controller\ExceptionController::exception
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    #fragments: true
    php_errors:
        log: true


#    workflows:
#        my_workflow:
        # ...

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
