framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    default_locale: '%app_locale%'
    translator:
        fallbacks: [ 'en', 'ru' ]
        cache_dir: null

    secrets:
        vault_directory: '%kernel.project_dir%/config/secrets/%kernel.environment%'
        local_dotenv_file: '%kernel.project_dir%/.env.%kernel.environment%.local'
        decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/config/validation/"
        not_compromised_password: true # in prod must by of true
#         validator.mapping.cache.doctrine.apc  # Симфони кеш
#    error_controller: App\Controller\ExceptionController::exception
    session:
        enabled: true
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    php_errors:
        log: true

