parameters:
  app_offline: '0'
  app_offline_message: 'Сайт закрыт на техническое обслуживание.<br />Пожалуйста, зайдите позже.'
  app_display_offline_message: '1'
  app_offline_image: ''
  app_sitename: '...ISponsor!'
  app_editor: 'tinymce'
  app_captcha: '0'
  app_list_limit: '20'
  app_access: '1'
  app_debug: '0'
  app_debug_lang: '0'
  app_debug_lang_const: '1'
  app_dbtype: 'mysqli'
  app_host: 'localhost'
  app_user: ''
  app_password: ''
  app_db: ''
  app_dbprefix: ''
  app_live_site: 'https://smartresponsor.com'
  app_gzip: '0'
  app_error_reporting: 'none'
  app_help_url: 'https://help.smartesponsor.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}'
  app_doc_url: 'https://doc.smartesponsor.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}'
  app_offset: 'UTC'
  app_force_ssl: '2'
  app_log_path: '/var/www/k924/data/www/smartresponsor-secret/administrator/logs'
  app_tmp_path: '/var/www/k924/data/www/smartresponsor-secret/tmp'
  app_lifetime: '15'
  app_session_handler: 'none'
  app_shared_session: '0'
  app_proxy_enable: '0'
  app_proxy_host: ''
  app_proxy_port: ''
  app_proxy_user: ''
  app_proxy_pass: ''
  app_massmailoff: '1'
  app_asset_id: '1'
  app_cookie_domain: '.smartresponsor.com'
  app_cookie_path: ''
  app_MetaRights: ''
  app_feed_limit: '10'
  app_feed_email: 'none'
  app_unicodeslugs: '0'
  app_sef: '1'
  app_sef_rewrite: '1'
  app_sef_suffix: '0'
