parameters:
  app_email_sender: 'taa0662621456@gmail.com'
  app_email_sender_name: '...iSponsor! Marketing America Corporation'
  app_notification_email_sender: 'taa0662621456@gmail.com'
  app_property: 'email'
  app_mailonline: '1'
  app_mailer: 'mail'
  app_mailfrom: 'taa0662621456@smartresponsor.com'
  app_fromname: '...I Sponsor! - crowdfunding platform'
  app_sendmail: '/usr/sbin/sendmail'
  app_smtpauth: '0'
  app_smtpuser: '%env(resolve:SMTP_USER)%'
  app_smtppass: '%env(resolve:SMTP_PASS)%'
  app_smtphost: 'localhost'
  app_smtpsecure: 'none'
  app_smtpport: '25'
  app_reply_to: 'taa0662621456@smartresponsor.com'
  app_reply_to_name: '...I Sponsor!'
