monolog:
    channels:
        - deprecation
        - database_setup

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ["!event", "!database_setup"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!database_setup"]
            database_setup:
                type: stream
                path: "%kernel.logs_dir%/database_setup_dev.log"
                level: debug
                channels: ["database_setup"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!database_setup"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            database_setup:
                type: stream
                path: "%kernel.logs_dir%/database_setup_test.log"
                level: debug
                channels: ["database_setup"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!database_setup"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            database_setup:
                type: stream
                path: "%kernel.logs_dir%/database_setup.log"
                level: info
                channels: ["database_setup"]
