framework:
    notifier:
        chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
            telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['sms', 'telegram', 'email']
            high: ['sms', 'telegram', 'email']
            medium: ['telegram', 'email']
            low: ['browser']
        admin_recipients:
            - { email: taa0662621456@gmail.com }

            # TODO: сделать браузерные уведомления
            # browserNotifier: '%env(MERCURE_DSN)%'
            # help https://symfony.com/bundles/ux-notify/current/index.html

