parameters:
  order_permission_matrix:
    ROLE_ADMIN: [VIEW, EDIT, DELETE, CANCEL, REFUND, PAY]
    ROLE_MANAGER: [VIEW, EDIT, DELETE, CANCEL, REFUND]
    ROLE_VENDOR: [VIEW, EDIT, DELETE, CANCEL, REFUND]
    ROLE_CUSTOMER: [VIEW, EDIT, CANCEL, PAY]
