parameters:
  app_name: '...iSponsor!'
  app_version: '0.0.0'
  app_domain: 'smartresponsor.com'
  app_schema: 'https'
  app_homepage_route: homepage
  app_login_route: login
  app_logout_route: logout
  app_default_target_path: project
  app_logged_out_target_route: homepage
  app_locales: en|ru|uk
  app_locale: 'en'
  app_locale_filter: 'en-US'
  app_homepage_number_of_items: 10
  app_logo_url: '/favicon.ico'
  app_category_images_directory: '%env(APP_CATEGORY_IMAGE_DIRECTORY)%'
  app_menu_images_directory: '%env(APP_MENU_IMAGE_DIRECTORY)%'
  app_project_images_directory: '%env(APP_PROJECT_IMAGE_DIRECTORY)%'
  app_product_images_directory: '%env(APP_PRODUCT_IMAGE_DIRECTORY)%'
  app_event_images_directory: '%env(APP_EVENT_IMAGE_DIRECTORY)%'
  app_vendor_images_directory: '%env(APP_VENDOR_IMAGES_DIRECTORY)%'
  app_vendor_profile_avatar_directory: '%env(APP_VENDOR_PROFILE_AVATAR_DIRECTORY)%'
