#parameters:
#    password_generator_config:
#        upper_case: true
#        lower_case: true
#        numbers: true
#        symbols: true
#        length: 12
#
#services:
#    App\Service\Security\PasswordGenerator:
#        arguments:
#            $config: '%password_generator_config%'
