services:
  Redis:
    class: Redis
    calls:
      - connect:
          - localhost
          - '%env(int:REDIS_PORT)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'
