services:
  # Doctrine entity listeners
  App\EventListener\CustomerEmailUpdaterListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\User, event: postUpdate }

  App\EventListener\VendorEmailUpdaterListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Vendor, event: postUpdate }

  App\EventListener\OrderRecalculationListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Order\OrderStorage, event: prePersist }
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Order\OrderStorage, event: preUpdate }

  App\EventListener\PasswordUpdaterListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\User, event: prePersist }
      - { name: doctrine.orm.entity_listener, entity: App\Entity\User, event: preUpdate }

  App\EventListener\ProductAttributeChoiceListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Product\ProductAttribute, event: postUpdate }

  App\EventListener\ProductAttributeListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Product\ProductAttribute, event: postUpdate }

  # Kernel event listeners
  App\EventListener\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

  App\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\EventListener\ZoneMatcherListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 300 }

  App\EventListener\LastRequestControllerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  App\EventListener\LastRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  App\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.controller }

  App\EventListener\NonChannelLocaleListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
