framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []


# https://question-it.com/questions/3145815/proverka-ogranichenij-symfony-5-nastrojka-soobschenija-ob-oshibke
#    App\Entity\User:
#        constraints:
#            - App\Validator\Constraints\ConstraintPassword: ~
#        properties:
#            plainPassword:
#                - Symfony\Component\Validator\Constraints\NotCompromisedPassword: ~
