framework:
    workflows:
        enabled: true
        workflows:
            order_state_workflow:
                type: state_machine
                audit_trail:
                    enabled: true
                marking_store:
                    type: method
                    property: 'getCurrentState'
                supports:
                    - App\Entity\Order\OrderStorage
                places:
                    - cart
                    - new
                    - processing
                    - completed
                    - failed
                    - canceled
                    - refunded
                transitions:
                    create:
                        from: cart
                        to: new
                    process:
                        from: [new, processing]
                        to: processing
                    complete:
                        from: processing
                        to: completed
                    fail:
                        from: processing
                        to: failed
                    cancel:
                        from: [new, processing]
                        to: canceled
                    refund:
                        from: completed
                        to: refunded
