GET https://{{host}}/
Accept: application/json
###
GET https://{{host}}/login
Accept: application/json
Authorization: Basic {{username}} {{password}}

###
GET https://{{host}}/en
Accept: application/json
###
GET https://{{host}}/project
Accept: application/json
###
GET https://{{host}}/en/project
Accept: application/json
###
GET https://{{host}}/project/new
Accept: application/json
###
GET https://{{host}}/product
Accept: application/json
###
GET https://{{host}}/product/new
Accept: application/json
###


