sylius_api:
    resource: .
    type: api_platform
    prefix: /

backend_authentication_token:
    path: /backend/authentication-token
    methods: ['POST']

frontend_authentication_token:
    path: /frontend/authentication-token
    methods: ['POST']
