sylius_api:
    resource: .
    type: api_platform
    prefix: /

backend_authentication_token:
    path: /admin/authentication-token
    methods: ['POST']

frontend_authentication_token:
    path: /shop/authentication-token
    methods: ['POST']
