<?php


namespace App\Repository\Project;

use App\Entity\Project\ProjectFavourite;
use App\Entity\Vendor\VendorFavourite;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ProjectsFavouritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFavouriteRepository extends EntityRepository
{
    /**
     * @param VendorFavourite $vendor
     * @param integer $projectId
     *
     * @return bool|null
     * @throws NonUniqueResultException
     * @throws \Doctrine\ORM\NoResultException
     */
	public function checkIsLiked(VendorFavourite $vendor, int $projectId): ?bool
	{
		$qb = $this->getEntityManager()
			->createQueryBuilder()
			->select('count(f.id)')
			->from(ProjectFavourite::class, 'f')
			->innerJoin('f.createBy', 'v')
			->innerJoin('f.project', 'p')
			->where('v = :createBy')
			->andWhere('p.id = :project_id')
			->setParameters([
				'project_id' => $projectId,
				'vendor' => $vendor
			]);

		if ($qb->getQuery()->getSingleScalarResult()) {
			return true;
		}

		return false;
	}
}
