#admin_zone:
#    resource: |
#        alias: zone
#        section: admin
#        templates: "@SyliusAdmin\\Crud"
#        except: ['show', 'create']
#        redirect: update
#        grid: admin_zone
#        permission: true
#        vars:
#            all:
#                subheader: ui.manage_geographical_zones
#                templates:
#                    form: "@SyliusAdmin/Zone/_form.html.twig"
#            index:
#                icon: world
#    type: resource

admin_zone_create:
    path: /zones/{type}/new
    methods: [GET, POST]
    defaults:
        _controller: controller.zone::createAction
        _sylius:
            section: admin
            factory:
                method: createTyped
                arguments:
                    type: $type
            template: "@SyliusAdmin/Crud/create.html.twig"
            redirect: admin_zone_update
            permission: true
            vars:
                subheader: ui.manage_geographical_zones
                templates:
                    form: "@SyliusAdmin/Zone/_form.html.twig"
                route:
                    parameters:
                        type: $type
    requirements:
        type: country|province|zone
