controllers:
    resource: ../../src/Controller/
    type: annotation
    requirements:
        _locale: '%app_locale%'
    defaults:
        _locale: '%app_locale%'
#annot:
#    resource: "@AnnotRoutingBundle/Controller"
#    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
