shipment_method:
    resource: |
        alias: sylius.shipping_method
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: shipment_method
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_shipping_methods_for_your_store
                templates:
                    form: "@SyliusAdmin/ShippingMethod/_form.html.twig"
            index:
                icon: shipping
    type: sylius.resource

shipment_method_archive:
    path: /shipping-methods/{id}/archive
    methods: [PATCH]
    defaults:
        _controller: sylius.controller.shipping_method::updateAction
        _sylius:
            section: admin
            permission: true
            template: '@SyliusUi/Grid/Action/archive.html.twig'
            form:
                type: Sylius\Bundle\ResourceBundle\Form\Type\ArchivableType
            redirect:
                route: shipment_method_index
                parameters: {}
