account_root:
    path: /
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: account_dashboard
        permanent: true

account_dashboard:
    path: /dashboard
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::showAction
        _sylius:
            template: "@SyliusShop/Account/dashboard.html.twig"
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"

account_profile_update:
    path: /profile/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.customer::updateAction
        _sylius:
            template: "@SyliusShop/Account/profileUpdate.html.twig"
            form: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"
            redirect:
                route: account_profile_update
                parameters: {}

account_change_password:
    path: /change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user::changePasswordAction
        _sylius:
            template: "@SyliusShop/Account/changePassword.html.twig"
            redirect: account_dashboard
