order:
    resource: |
        alias: order
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        grid: order
        permission: true
        vars:
            all:
                subheader: ui.process_your_orders
            index:
                icon: cart
    type: resource

order_show:
    path: /orders/{id}
    methods: [GET]
    defaults:
        _controller: controller.order::showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Order/show.html.twig"

order_history:
    path: /orders/{id}/history
    methods: [GET]
    defaults:
        _controller: controller.order::showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Order/history.html.twig"

order_update:
    path: /orders/{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: controller.order::updateAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Order/update.html.twig"
            form:
                options:
                    validation_groups:
                        - sylius_shipping_address_update

order_cancel:
    path: /orders/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: controller.order::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: sylius_order
                transition: cancel
            redirect: referer

order_payment_complete:
    path: /orders/{orderId}/payments/{id}/complete
    methods: [PUT]
    defaults:
        _controller: controller.payment::applyStateMachineTransitionAction
        _sylius:
            event: complete
            permission: true
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_payment
                transition: complete
            redirect: referer

order_payment_refund:
    path: /orders/{orderId}/payments/{id}/refund
    methods: [PUT]
    defaults:
        _controller: controller.payment::applyStateMachineTransitionAction
        _sylius:
            permission: true
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_payment
                transition: refund
            redirect: referer
            flash: payment.refunded

order_shipment_ship:
    path: /{id}/ship
    methods: [PUT]
    defaults:
        _controller: controller.shipment::updateAction
        _sylius:
            event: ship
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_shipment
                transition: ship
            redirect: referer
            section: admin
            permission: true
            form: Sylius\Bundle\ShippingBundle\Form\Type\ShipmentShipType
            vars:
                route:
                    parameters:
                        orderId: $orderId
                        id: $id

order_resend_confirmation_email:
    path: /{id}/resend-confirmation-email
    methods: [GET]
    defaults:
        _controller: Sylius\Bundle\AdminBundle\Action\ResendOrderConfirmationEmailAction
