order_thank_you:
    path: /thank-you
    methods: [GET]
    defaults:
        _controller: controller.order::thankYouAction
        _sylius:
            template: "@SyliusShop/Order/thankYou.html.twig"

order_pay:
    path: /{tokenValue}/pay
    methods: [GET]
    defaults:
        _controller: controller.payum::prepareCaptureAction
        _sylius:
            redirect:
                route: order_after_pay

order_after_pay:
    path: /after-pay
    methods: [GET, POST]
    defaults:
        _controller: controller.payum::afterCaptureAction

order_show:
    path: /{tokenValue}
    methods: [GET, PUT]
    defaults:
        _controller: controller.order::updateAction
        _sylius:
            template: "@SyliusShop/Order/show.html.twig"
            repository:
                method: findOneBy
                arguments: [tokenValue: $tokenValue]
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectPaymentType
                options:
                    validation_groups: []
            redirect:
                route: order_pay
                parameters:
                    tokenValue: resource.tokenValue
            flash: false
