framework:
    ide: 'phpstorm://open?file=file://%%f&line=%%l'
    disallow_search_engine_index: true
    trusted_hosts: ['%env(TRUSTED_HOSTS)%', '127.0.0.1', 'localhost', 'smartresponsor.com']
    profiler: true
    default_locale: '%app_locale%'
