monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
#            formatter: App\Service\Monolog\ExceptionWithClassFormatter
        exception_log:
            type: stream
            path: "%kernel.logs_dir%/exceptions.log"
            level: error
#            formatter: App\Service\Monolog\ExceptionWithClassFormatter
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
