<?php
declare(strict_types=1);

namespace App\Repository;

use App\Entity\Vendors;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * VendorsFavouritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorsFavouritesRepository extends EntityRepository
{
    /**
     * @param Vendors $vendor
     * @param integer $vendorId
     * @return bool
     * @throws NonUniqueResultException
     */
    public function checkIsLiked($vendor, $vendorId): ?bool
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(f.id)')
            ->from(':VendorsFavourites', 'f')
            ->innerJoin('f.vendor', 'v')
            ->innerJoin('f.vendor', 'p')
            ->where('v = :vendor')
            ->andWhere('p.id = :vendor_id')
            ->setParameters([
                'vendor_id' => $vendorId,
                'vendor' => $vendor
            ]);

        if ($qb->getQuery()->getSingleScalarResult()) {
            return true;
        }

        return false;
    }
}
