currency_exchange_rate:
    resource: |
        alias: exchange_rate
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_exchange_rate
        permission: true
        vars:
            all:
                subheader: ui.manage_exchange_rates
                templates:
                    form: "@SyliusAdmin/ExchangeRate/_form.html.twig"
            index:
                icon: sliders
    type: resource
