version: "3.9"

networks:
  backend:

volumes:
  pgdata:
  esdata:

services:
  php:
    build: ./php
    networks: [backend]
    volumes:
      - ../:/var/www/symfony:cached
    environment:
      APP_ENV: dev
    depends_on:
      - db
      - redis
      - rabbitmq
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK';"]
      interval: 30s
      timeout: 10s
      retries: 3

  caddy:
    build: ./caddy
    networks: [backend]
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/symfony:cached
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    build: ./db
    networks: [backend]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    build: ./redis
    networks: [backend]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    networks: [backend]
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-symfony}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-symfony}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    networks: [backend]
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ftp:
    image: fauria/vsftpd
    networks: [backend]
    environment:
      - FTP_USER=${FTP_USER:-symfony}
      - FTP_PASS=${FTP_PASS:-symfony}
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS=127.0.0.1
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ../:/home/vsftpd
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 21 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  node:
    build: ./node
    networks: [backend]
    working_dir: /var/www/symfony
    volumes:
      - ../:/var/www/symfony
    healthcheck:
      test: ["CMD", "node", "-v"]
      interval: 60s
      timeout: 10s
      retries: 3
