framework:
  http_client:
    default_options:
      retry_failed:
        jitter: 0.1
      max_duration: 29000
      max_redirects: 3
  profiler: false
  mailer:
    dsn: sendmail://default
    envelope:
      recipients: [ 'taa0662621456@gmail.com' ]
  validation:
    email_validation_mode: strict # Can be loose, html5, strict (for strict must be add: egulias/email-validator )
    not_compromised_password: true # in dev must by of false

  error_controller: App\Controller\ExceptionController::exception
