framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: false
  default_locale: '%app_locale%'

  not_compromised_password: true # in dev must by of false
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
