parameters:
  app_name: '...iSponsor!'
  app_version: '0.0.0'
  app_domain: 'smartresponsor.com'
  app_schema: 'https'
  app_homepage_routename: 'homepage'
  app_login_page_routename: 'login'
  app_logout_routename: 'logout'
  app_logged_in_target_routename: 'homepage'
  app_logged_out_target_routename: 'homepage'
  app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt
  app_locale: 'en'
  app_cache: 0
  app_cache_time: 360
  app_email_sender: 'taa0662621456@gmail.com'
  app_notifications_email_sender: 'taa0662621456@gmail.com'
  app_property: 'email'
  app_akismet_key: 'weqweqweDFDFDFFDwqeqwewqewqe'
  app_csrf_token: 'weqweqweDFDFDFFDwqeqwewqewqe'
  app_homepage_number_of_items: 10
  app_logo_url: '/favicon.ico'
  app_category_images_directory: '%kernel.project_dir%/public/uploads/categories/images'
  app_menu_images_directory: '%kernel.project_dir%/public/uploads/menus/images'
  app_project_images_directory: '%kernel.project_dir%/public/uploads/projects/images'
  app_product_images_directory: '%kernel.project_dir%/public/uploads/products/images'
  app_google_recaptcha_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  app_vendor_images_directory: '%kernel.project_dir%/public/uploads/vendors/images'
  mercure_secret_key: '%env(MERCURE_SECRET_KEY)%'
