payment_method:
    resource: |
        alias: payment_method
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: payment_method
        permission: true
        vars:
            all:
                subheader: ui.manage_payment_methods_available_to_your_customers
                templates:
                    form: "@SyliusAdmin/PaymentMethod/_form.html.twig"
            index:
                icon: payment
    type: resource

payment_method_create:
    path: /payment-methods/new/{factory}
    methods: [GET, POST]
    defaults:
        _controller: controller.payment_method::createAction
        _sylius:
            section: admin
            factory:
                method: createWithGateway
                arguments:
                    gatewayFactory: $factory
            template: "@SyliusAdmin/Crud/create.html.twig"
            redirect: payment_method_update
            permission: true
            vars:
                subheader: ui.manage_payment_methods_available_to_your_customers
                templates:
                    form: "@SyliusAdmin/PaymentMethod/_form.html.twig"
                route:
                    parameters:
                        factory: $factory

get_payment_gateways:
    path: /payment-gateways
    methods: [GET]
    defaults:
        _controller: controller.payment_method::getPaymentGatewaysAction
        template: "@SyliusAdmin/PaymentMethod/Gateways/paymentGateways.html.twig"
