payment:
    resource: |
        alias: payment
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        grid: payment
        permission: true
        vars:
            all:
                subheader: ui.manage_payments
            index:
                icon: payment
    type: resource

payment_complete:
    path: /payments/{id}/complete
    methods: [PUT]
    defaults:
        _controller: controller.payment::applyStateMachineTransitionAction
        _sylius:
            event: complete
            section: admin
            permission: true
            state_machine:
                graph: sylius_payment
                transition: complete
            redirect: referer
            flash: payment.completed
