#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect

facebook_login:
  path: /login/check-facebook

google_login:
  path: /login/check-google

github_login:
  path: /login/check-github
