imports:
  - { resource: packages/parameters.yaml }
  - { resource: packages/security_parameters.yaml }
  - { resource: packages/mailer_parameters.yaml }
  - { resource: packages/cache_parameters.yaml }
  - { resource: packages/seo_parameters.yaml }
  - { resource: packages/legacy_parameters.yaml }
  - { resource: packages/services_order.yaml }
  - { resource: packages/services_listeners.yaml }
  - { resource: packages/services_subscribers.yaml }
  - { resource: packages/services_security.yaml }
  - { resource: packages/services_mailer.yaml }
  - { resource: packages/services_cache.yaml }

parameters:
  container.dumper.inline_factories: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $locales: '%app_locales%'
      string $locale: '%app_locale%'
      string $pathToEntity: 'App\\Entity\\'
      string $pathToRepository: 'App\\Repository\\'
      string $pathToType: 'App\\Form\\'
      string $pathToLogin: '%app_login_route%'
      string $pathToLoginSuccess: '%app_login_route%'
      string $token: '%app_csrf_token%'
      string $akismetKey: "%app_akismet_key%"

  App\\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
      - '../src/Trash/'
      - '../migrations/'

  App\\EventSubscriber\\:
    resource: '../src/EventSubscriber/*'
    tags: ['kernel.event_subscriber']
