imports:
#    - { resource: '%kernel.project_dir%/config/parameters.yaml', ignore_errors: true }
parameters:
    # Meta Data
    app_name: '...iSponsor!'
    app_version: '0.0.0'
    app_domain: 'smartresponsor.com'
    #
    # Redirect routs
    app_homepage_routename: 'homepage'
    app_login_page_routename: 'login'
    app_logout_routename: 'logout'
    app_logged_in_target_routename: 'homepage'
    app_logged_out_target_routename: 'homepage'
    # Localisation
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt
    app_locale: 'en'
    # Cache
    app_cache: 0
    app_cache_time: 360
    # Mailing
    app_email_sender: 'taa0662621456@gmail.com'
    app_notifications_email_sender: '%env(EMAIL_SENDER)%'
    app_property: 'email'
    # Akismet
    app_akismet_key: 'weqweqweDFDFDFFDwqeqwewqewqe'
    # CSRF
    app_csrf_token: 'weqweqweDFDFDFFDwqeqwewqewqe'
    # Oder parameters
    app_homepage_number_of_items: 10
    app_logo_url: '/favicon.ico'
    app_schema: 'https'
    app_secret: '%env(APP_SECRET)%'
    app_google_recaptcha_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    # Media folders parameters
    app_category_image_directory: '%env(APP_CATEGORY_IMAGE_DIRECTORY)%'
    app_menu_image_directory: '%env(APP_MENU_IMAGE_DIRECTORY)%'
    app_project_image_directory: '%env(APP_PROJECT_IMAGE_DIRECTORY)%'
    app_product_image_directory: '%env(APP_PRODUCT_IMAGE_DIRECTORY)%'
    app_vendor_image_directory: '%env(APP_VENDOR_IMAGE_DIRECTORY)%'
    # Mercure
    app_mercure_hub_url: '%env(MERCURE_HUB_URL)%'
    app_mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'
    app_mercure_key: '%env(MERCURE_KEY)%'
    app_mercure_secret: '%env(MERCURE_SECRET)%'
    #
    # router.request_context.host: '%env(default:default_domain:SYMFONY_DEFAULT_ROUTE_HOST)%'
    # router.request_context.scheme: '%env(default:default_scheme:SYMFONY_DEFAULT_ROUTE_SCHEME)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
#            string $app: '%kernel.project_dir%'
            string $locales: '%app_locales%'
            string $locale: '%app_locale%'
            string $pathToEntity: 'App\Entity\'
            string $pathToRepository: 'App\Repository\'
            string $pathToType: 'App\Form\'
            string $pathToLogin: '%app_login_page_routename%'
            string $pathToLoginSuccess: '%app_login_page_routename%'
            string $token: '%app_csrf_token%'
#            $emailSender: '%app_email_sender%'
#            $akismetKey: "%env(AKISMET_KEY)%"
#            $adminEmail: "%env(string:default:app_email_sender:ADMIN_EMAIL)%"
#            string $projectImageAttachmentsPath: "%app_project_images_directory%"
#            string $productImageAttachmentsPath: "%app_product_images_directory%"
#            string $categoryImageAttachmentsPath: "%app_category_images_directory%"
#            string $vendorImageAttachmentsPath: "%app_vendor_images_directory%"
#            string $daysBeforeRemoveRejectedReview: ""

    App\EventSubscriber\LocaleSubscriber:
#        arguments: [ '%kernel.default_locale%' ]
        arguments: [ '%app_locale%' ]
#         tags: [kernel.event_subscriber] # uncomment the next line if you are not using autoconfigure

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Trash/'
            - '../migrations/'
