    # router.request_context.host: '%env(default:default_domain:SYMFONY_DEFAULT_ROUTE_HOST)%'
    # router.request_context.scheme: '%env(default:default_scheme:SYMFONY_DEFAULT_ROUTE_SCHEME)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
#            string $app: '%kernel.project_dir%'
            string $locales: '%app_locales%'
            string $locale: '%app_locale%'
            string $pathToEntity: 'App\Entity\'
            string $pathToRepository: 'App\Repository\'
            string $pathToType: 'App\Form\'
            string $pathToLogin: '%app_login_page_routename%'
            string $pathToLoginSuccess: '%app_login_page_routename%'
            string $token: '%app_csrf_token%'
#            $emailSender: '%app_email_sender%'
#            $akismetKey: "%env(AKISMET_KEY)%"
#            $adminEmail: "%env(string:default:app_email_sender:ADMIN_EMAIL)%"
#            string $projectImageAttachmentsPath: "%app_project_images_directory%"
#            string $productImageAttachmentsPath: "%app_product_images_directory%"
#            string $categoryImageAttachmentsPath: "%app_category_images_directory%"
#            string $vendorImageAttachmentsPath: "%app_vendor_images_directory%"
#            string $daysBeforeRemoveRejectedReview: ""

    App\EventSubscriber\LocaleSubscriber:
        arguments: [ '%kernel.default_locale%' ]
#         tags: [kernel.event_subscriber] # uncomment the next line if you are not using autoconfigure

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Trash/'
            - '../migrations/'
