product_attribute:
    resource: |
        alias: product_attribute
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show', 'create']
        redirect: update
        grid: product_attribute
        permission: true
        vars:
            all:
                subheader: ui.manage_attributes_of_your_products
                templates:
                    form: "@SyliusAdmin/ProductAttribute/_form.html.twig"
            index:
                icon: cubes
    type: resource

product_attribute_create:
    path: /product-attributes/{type}/new
    methods: [GET, POST]
    defaults:
        _controller: controller.product_attribute::createAction
        _sylius:
            section: admin
            factory:
                method: createTyped
                arguments:
                    type: $type
            template: "@SyliusAdmin/Crud/create.html.twig"
            redirect: product_attribute_update
            permission: true
            vars:
                subheader: ui.manage_attributes_of_your_products
                templates:
                    form: "@SyliusAdmin/ProductAttribute/_form.html.twig"
                route:
                    parameters:
                        type: $type

get_attribute_types:
    path: /attribute-types
    methods: [GET]
    defaults:
        _controller: controller.product_attribute::getAttributeTypesAction
        template: "@SyliusAdmin/ProductAttribute/Types/attributeTypes.html.twig"

get_product_attributes:
    path: /attributes
    methods: [GET]
    defaults:
        _controller: controller.product_attribute::renderAttributesAction
        template: "@SyliusAdmin/Product/Attribute/attributeChoice.html.twig"

render_attribute_forms:
    path: /attribute-forms
    methods: [GET]
    defaults:
        _controller: controller.product_attribute::renderAttributeValueFormsAction
        template: "@SyliusAdmin/Product/Attribute/attributeValues.html.twig"
