security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security::loginAction
        _sylius:
            template: "@SyliusShop/login.html.twig"
            logged_in_route: security_account_dashboard

security_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security::checkAction

security_logout:
    path: /logout
    methods: [GET]

security_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer::createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: security_account_dashboard
            flash: sylius.customer.register

security_register_after_checkout:
    path: /register-after-checkout/{tokenValue}
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::createAction
        _sylius:
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            factory:
                method: ['expr:service("sylius.factory.customer_after_checkout")', 'createAfterCheckout']
                arguments:
                    - 'expr:service("sylius.repository.order").findOneByTokenValue($tokenValue)'
            template: "@SyliusShop/register.html.twig"
            event: register
            redirect:
                route: security_account_dashboard
            flash: sylius.customer.register

security_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user::requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: security_login

security_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user::resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: security_login
