security_request_verification_token:
    path: /verify
    methods: [POST]
    defaults:
        _controller: controller.shop_user::requestVerificationTokenAction

security_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: controller.shop_user::verifyAction
        _sylius:
            redirect: sylius_shop_account_dashboard
