name: Send Diff to ChatGPT
on:
  push:
    branches:
      - master
      - develop

jobs:
  send_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get diff
        run: |
          git fetch origin
          git diff HEAD~1 HEAD > diff.patch

      - name: Send diff to ChatGPT
        run: |
          curl -X POST "https://api.openai.com/v1/files" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -F "purpose=assistants" \
            -F "file=@diff.patch"
