name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        db: [postgres, mysql]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
          POSTGRES_DB: symfony_test
        ports:
          - 5432:5432

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: |
          if [[ "${{ matrix.db }}" == "postgres" ]]; then
            echo "DATABASE_URL=postgresql://symfony:symfony@127.0.0.1:5432/symfony_test" >> .env.test.local
          else
            echo "DATABASE_URL=mysql://symfony:symfony@127.0.0.1:3306/symfony_test" >> .env.test.local
          fi
      - run: php bin/console doctrine:migrations:migrate --no-interaction --env=test
      - run: |
          php bin/console fixtures:load-group core --append --env=test
          php bin/console fixtures:load-group catalog --append --env=test
      - run: make test

  coverage:
    runs-on: ubuntu-latest
    needs: php-tests

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
          POSTGRES_DB: symfony_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: composer:v2
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: echo "DATABASE_URL=postgresql://symfony:symfony@127.0.0.1:5432/symfony_test" >> .env.test.local
      - run: php bin/console doctrine:migrations:migrate --no-interaction --env=test
      - run: php bin/console fixtures:load-group core --append --env=test
      - run: |
          mkdir -p coverage
          vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-html=coverage/

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/

      - name: Deploy coverage to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: gh-pages
          destination_dir: coverage
